Adding styles
Tekcoder/newyorktimes-article-page pull request #1
Opened 2019-09-23 16:20 UTC by mrnadaara

2019-09-23 19:25 UTC, whiz25 commented on index.html
> +        <button>Log In</button>
Make this button should be in line with the main logo

2019-09-23 19:26 UTC, whiz25 commented on index.html
> +        <button>Subscribe Now</button>
Make this aligned on the same row as the logo.

2019-09-23 19:32 UTC, whiz25 requested changes
## Good job so far team :thumbsup:
However, we need to make the following changes before the project gets completed.
- [ ] I don't see your ```The Theory of Inflation``` section. This is required.
- [ ] Add the embedded video
- [ ] Add also the ```More in Space & Cosmos``` section
- [ ] Add a footer and links to other articles as well.

Make the changes and re-submit for another review.
## Just make your page look as close to the original page [here](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html) as possible

2019-09-26 00:40 UTC, Redvanisation requested changes
### Hello @mrnadaara and @Tekcoder   🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. The **navbar** should have a **fixed CSS position**.

2. The **footer** also should have a **fixed CSS position**.

### _After making the required changes please submit a new code review request_

### Good luck guys! 🍀

2019-09-26 17:15 UTC, uche-inyama approved these changes
### Nice, you have implemented the requested changes. :slightly_smiling_face: 

#### Go ahead and merge to master branch :rocket:

2019-09-26 17:19 UTC, merged